import { createSlice } from "@reduxjs/toolkit";

const postSlice = createSlice({
  name: "post",
  initialState: {
    currentPost: null,
  },
  reducers: {
    setPost: (state, action) => {
      state.currentPost = action.payload;
    },
  },
});

export const { setPost } = postSlice.actions;
export default postSlice.reducer;

/**
 * createSlice is a utility from Redux Toolkit that automatically generates action creators and reducers for you.
 * A slice represents a specific piece of the Redux state and the reducers (functions) that update that piece of state.
 */

/**
 * postSlice.actions
 * This object contains all the action creators automatically generated by "createSlice"
 * Each key in this object corresponds to one of the reducer functions you defined.
 * "setPost" is an "action creator" that you can dispatch to update the state
 */
